window.SPIRITVALE_MAPS = [
  { name: "Forest Labyrinth 1", level: "Safe zone" },
  { name: "Forest Labyrinth 2", level: "Safe zone" },
  { name: "Forest Labyrinth 3", level: "Safe zone" },
  { name: "Forest Labyrinth 4", level: "Safe zone" },
  { name: "Nevaris", level: "Safe zone" },
  { name: "The Echoing Spire", level: "Safe zone" },
  { name: "Wayfarer's Landing", level: "Safe zone" },
  { name: "Sunny Meadows 1", level: "Lv 1–5" },
  { name: "Sunny Meadows 2", level: "Lv 6–10" },
  { name: "Forest Field 1", level: "Lv 11–15" },
  { name: "Forest Field 2", level: "Lv 16–20" },
  { name: "Nevaris Sewers", level: "Lv 16–20" },
  { name: "Treant Trail", level: "Lv 16–20" },
  { name: "Bunny Woods", level: "Lv 21–25" },
  { name: "Festering Woods 1", level: "Lv 21–25" },
  { name: "Festering Woods 2", level: "Lv 26–30" },
  { name: "Lake Field", level: "Lv 26–30" },
  { name: "Windy Desert", level: "Lv 26–30" },
  { name: "Fairy Glen", level: "Lv 31–35" },
  { name: "Mystic Lake 1", level: "Lv 31–35" },
  { name: "Windy Desert North", level: "Lv 31–35" },
  { name: "Windy Desert South", level: "Lv 31–35" },
  { name: "Mystic Lake 2", level: "Lv 36–40" },
  { name: "Swamp", level: "Lv 36–40" },
  { name: "Forgotten Depths 1", level: "Lv 41–45" },
  { name: "Goblin Field", level: "Lv 41–45" },
  { name: "Forgotten Depths 2", level: "Lv 46–50" },
  { name: "Goblin Village", level: "Lv 46–50" },
  { name: "Goblin Cave 1", level: "Lv 51–55" },
  { name: "Goblin Cave 2", level: "Lv 56–60" },
  { name: "Stormreef Isle", level: "Lv 61–65" },
  { name: "Crystal Cave", level: "Lv 66–70" },
  { name: "Swamp Wilderness", level: "Lv 71–75" },
  { name: "Sanctum of Light 1", level: "Lv 76–80" },
  { name: "Sanctum of Light 2", level: "Lv 81–85" },
  { name: "Underground Cavern", level: "Lv 86–90" },
  { name: "Dark Forest", level: "Lv 91–95" },
  { name: "Demon's Maw", level: "Lv 96–100" },
  { name: "Sunken Depths", level: "Lv 101–105" },
  { name: "Sunken Depths 2", level: "Lv 101–105" },
  { name: "Abyss Castle Dungeon", level: "Lv 106–110" },
  { name: "Abyss Castle Keep", level: "Lv 111–115" },
  { name: "Abyss Castle Crypt", level: "Lv 116–120" },
  { name: "Abyss Castle Library", level: "Lv 121–125" },
  { name: "Goblin Warcamp", level: "Lv 121–125" },
  { name: "Night Garden", level: "Lv 126–130" },
  { name: "The Forge", level: "Lv 126–130" },
  { name: "Starfall Tundra", level: "Lv 131–135" },
  { name: "Turtle Nexus", level: "Lv 131–135" },
  { name: "Dark Manor", level: "Lv 141–145" },
  { name: "Dark Fotress", level: "Lv 145–150" },		
];
